version: '3'
services:
  meshconsumer:
    build:
      context: dubbo-consumer-mesher/
      dockerfile: Dockerfile
    # environment:
      # - CSE_REGISTRY_ADDR=http://serveraddress:30100
  dubboconsumer:
    build:
      context: dubbo-consumer/
      dockerfile: Dockerfile
    network_mode: "service:meshconsumer"
    depends_on: 
      - "meshconsumer"

