version: '3'
services:

  meshprovider:
    build:
      context: dubbo-provider-mesher/
      dockerfile: Dockerfile
    environment: 
      - CSE_REGISTRY_ADDR=http://serveraddress:30100

  provider:
    build:
      context: dubbo-provider/
      dockerfile: Dockerfile
    network_mode: "service:meshprovider"
    depends_on: 
      - "meshprovider"
